%YAML:1.0
---

#image/geotiff path
perspective_img_path: "nbd_real_east.jpg"
orthophoto_img_path: "nbd1cm.jpg"
geotiff_path: "nbd1cm.tif"

#perspective/othophoto mask path
perspective_mask_path: ""
orthophoto_mask_path: "nbd_real_west_mask.png"

orthophoto_img_scale: 1.0

#set if require marker as assistance
is_need_marker: "false"
marker_config_file: "marker_config.yml"
marker_pt_to_ASIFT_pt_ratio: 1

#add points pair by matching manually (usually far point pair)
#additional_points_pair_file: "src_dst_points_xian3cmtrue.yml"
#additional_points_pair_file: "src_dst_points_xian3cmtrue_south.yml"
additional_points_pair_file: ""

#maximum threads to be used in matching, decrease it if RAM is not enough to run
max_threads_used: 2
#ratio for filtering false matching, not much use to change it
SIFT_ratio: 0.65
#number of random sample for finding the best homography matrix
RANSAC_iteration_num: 5000000
#reprojection threshold for finding the inliers to calculate the best homography matrix (in meter)
RANSAC_phy_reprojection_thres_in_m: 1.0
#maximum rms error threshold of matching (in meter)
max_rms_err_thres_in_m: 1.0

#set if require distortion correction
is_need_distortion_corr: "false"
#camera parameters if distortion correction is required
intrinsic_and_distortion_coeff_path: "intrinsic_and_distortion_coeff.yml"






